### ISSUE TITLE
do you have train log?

### ISSUE THREAD

**Issue by daixiangzi** [yshMars/DistilPose#5]

**Comment by yshMars** [comment]
Sure.
[DistilPose_S_train_log.log](https://github.com/yshMars/DistilPose/files/11958657/DistilPose_S_train_log.log)

**Comment by daixiangzi** [comment]
> Sure.
> [DistilPose_S_train_log.log](https://github.com/yshMars/DistilPose/files/11958657/DistilPose_S_train_log.log)

ok ,thank you ,I have other problem, student model load imagenet pretrain weight? or load weight from scratch train on coco? when train distilpose;

**Comment by daixiangzi** [comment]
can you offer config file based on deeppose?
